# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatfollower',
            name='nick_name',
            field=models.TextField(max_length=1024),
        ),
    ]
