# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_auto_20170604_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatUserHis',
            fields=[
                ('his_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ac_time', models.DateTimeField(auto_now=True)),
                ('boat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat.Boat')),
                ('open_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat.BoatFollower')),
            ],
        ),
    ]
