# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0004_auto_20170709_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_create_time',
            field=models.DateTimeField(),
        ),
    ]
