# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0005_auto_20170709_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatuserhis',
            name='ac_ctx',
            field=models.TextField(default=''),
        ),
    ]
