# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0006_boatuserhis_ac_ctx'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='boat_owner_nick_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
